<a href="https://colab.research.google.com/github/HayunSONG9758/DALC_Scala/blob/main/2_1_numpy_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy = Numerical Python
- 기본적으로 array 단위로 데이터 관리 및 연산 수행
- array : 동일한 데이터 타입을 갖는 벡터나 행렬

In [2]:
import numpy as np

In [4]:
data1 = [1,2,3,4,5]
data2 = [6,5,4,3,2,1]
print(data1, data2)

[1, 2, 3, 4, 5] [6, 5, 4, 3, 2, 1]


In [ ]:
ar1 = np.array(data1) #ar1에 numpy배열을 만들어 할당
ar1

array([1, 2, 3, 4, 5])

In [ ]:
#배열의 데이터 타입 지정

ar2 = np.array(data1, dtype = 'float32') #원래 data1은 정수요솟값이었으나, float32 = 실수 요솟값 사용함 
ar2 # 실수 데이터 갖는 배열 만들어짐

array([1., 2., 3., 4., 5.], dtype=float32)

In [5]:
# 다차원 배열 구성 다차원 배열 구성
ar3 = np.array([range(i, i+3) for i in data1])
ar3

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

In [ ]:
ar4 = np.full((3,5), 3.14) #full함수((행렬 크기), 지정값r4 = np.full((3,5), 3.14) #full함수((행렬 크기), 지정값)
ar4

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
ar5 = np.arange(0, 20, 2) # 20은 포함되지 않음 arange() = py.range() (완전 같은건 아니고 비슷...)
ar5

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
# linspace 함수
ar6 = np.linspace(0,1,3) #0과 1 사이에 (0.5간격의) 3개 요소값을 가진 배열 생성
ar6

array([0. , 0.5, 1. ])

In [8]:
#무작위 값의 배열 구성
ar7 = np.random.random((3,3)) #3X3행렬을 생성하고, 0과 1사이의 무작위 값으로 채움
ar7

array([[0.33794643, 0.86565909, 0.56540531],
       [0.38640802, 0.6049183 , 0.80647371],
       [0.85847927, 0.17408718, 0.47370968]])

In [9]:
ar8 = np.random.randint(0,100,(3,3)) # (구간의 시작, 구간의 끝,(배열 크기))
ar8

array([[31, 91, 29],
       [21, 26, 76],
       [18, 23, 81]])

In [10]:
# eye 함수
ar9 = np.eye(3) #대각선으로는 1이고 나머지는 0인 단위함수 만들 수 ㅇ 
ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

1) 배열 속성

In [11]:
import numpy as np
x = np.random.randint(10, size =(3,4,5))
x

array([[[1, 6, 1, 8, 7],
        [3, 0, 9, 0, 7],
        [9, 0, 3, 9, 2],
        [9, 3, 0, 3, 4]],

       [[1, 3, 0, 9, 1],
        [5, 9, 8, 3, 7],
        [9, 5, 4, 8, 4],
        [1, 1, 0, 6, 8]],

       [[7, 2, 7, 7, 6],
        [2, 2, 0, 3, 2],
        [1, 7, 9, 8, 5],
        [7, 0, 7, 8, 9]]])

In [12]:
print("x ndim:", x.ndim) #차원의 갯수
print("x shape:", x.shape) #각 차원의 크기
print("x size:", x.size) #전체 배열의 크기

x ndim: 3
x shape: (3, 4, 5)
x size: 60


2) 배열 인덱싱

In [13]:
y = np.array([2,4,6,8,10]) #리스트 인덱싱과 유사함
print(y[0], y[-2]) #음수 인덱스는 배열 가장 끝에서...

2 8


In [14]:
z = np.array([[2,4,6,8,10], [3,6,9,12,15]])
print(z[1,0])

3


In [15]:
z[0,0]=12 # 해당 위치의 요소값을 2-> 12로 변경
z

array([[12,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15]])

4) 배열 슬라이싱

In [ ]:
x[start:stop:step]
# start는 0으로 설정
# stop은 차원 크기로 설정
# step은 1로 설정

In [16]:
x = np.arange(10)
x[4:8]

array([4, 5, 6, 7])

In [17]:
x = np.arange(10)
x[:5]

array([0, 1, 2, 3, 4])

In [18]:
x = np.arange(10)
x[5:] # 인덱스 5 이후의 요소를 가진

array([5, 6, 7, 8, 9])

5) 다차원 배열 슬라이싱

In [19]:
z = np.array([[2,4,6,8], [3,6,9,12], [4,8,12,16]])
z[:2, :3] #인덱스 0,1행과 인덱스 0,1,2열로 구성되는 다차원 하위배열 생성

array([[2, 4, 6],
       [3, 6, 9]])

In [20]:
z = np.array([[2,4,6,8], [3,6,9,12], [4,8,12,16]])
z[:3, ::2] #모든 행마다 한 열씩 걸러 구성된 다차원 하위배열 형성

array([[ 2,  6],
       [ 3,  9],
       [ 4, 12]])

6) 배열 재구조화

In [21]:
#reshape 함수 : 배열의 형상을 변경하는 것
z = np.arange(1, 10).reshape(3, 3) #3X3 행렬에 숫자 1~9까지 넣고싶을 경우
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

7) 배열 결합

In [22]:
#concatenate
x = np.array([1,2,3])
y = np.array([3,2,1])
z = np.concatenate([x,y])
z

array([1, 2, 3, 3, 2, 1])

In [23]:
#vstack 수직 스택
x = np.array([1,2,3])
grid = np.array([[4,5,6],[7,8,9]])
v = np.vstack([x, grid]) #수직으로 하나로 합침
v

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
#hstack 수평 스택
y = np.array([[99],[[99]]])
z = np.hstack([grid, y])
z

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


array([[4, 5, 6, 99],
       [7, 8, 9, list([99])]], dtype=object)

8) 배열 분할

In [29]:
#split
x = [1,2,3,77,77,3,2,1]
x1,x2,x3 = np.split(x,[3,5]) #split(분할 대상 리스트, 분할 위치)
print(x1,x2,x3)

[1 2 3] [77 77] [3 2 1]


In [30]:
#vsplit
grid = np.arange(16).reshape((4,4))
upper, lower = np.vsplit(grid, [2]) #grid 배열이 상하 2개로 나뉨
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [32]:
#hsplit
grid = np.arange(16).reshape((4,4))
left, right = np.hsplit(grid, [2]) #grid 배열이 좌우 2개로 나뉨
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
